log:
  file: /var/log/serverstat.log
  level: debug

ssh:
  frequency: 3  # every 1 second
  default_password: zhouligang
  default_identityfile: ~/.ssh/id_rsa

servers:
  list:
    - hz_aliyun_01
    - aws_jp_01
    - oracle_jp_01
    - dell
